runtime: nodejs16

env_variables:
  MONGO_URI: mongodb://epicfondo:JJeCqecJQo3pbRBrmbLKzYZmbhHk38HO4GVo6JFWqHpxcoVSdCZywSr1AIS1jK61v4S4lP8Dv2dDACDbVzfgBA==@epicfondo.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@epicfondo@/epicfondo
  PORT: 8080

handlers:
  - url: /.*
    script: auto
